### ISSUE TITLE
nut code

### ISSUE THREAD

**Issue by ctaggart** [matthieudelaro/nut#10]
I'd like to be able to type `nut code` after I clone a project and get a Visual Studio Code environment with extensions for editing that project.

It would be great if I could put some of the nut options under a macro in `nut.yml`. Something like:
``` yaml
macros:
  code:
    docker-image: ctaggart/golang-vscode
    enable_gui: true
    mount:
      main:
      - .
      - /home/vscode/mygoproject
    usage: start vscode to edit this project
    actions:
    - su vscode -c "code -w /home/vscode/mygoproject"
```

This way I could clone mygoproject, run `nut code` and have it start Visual Studio Code with all the extensions I need to code. This would eliminate a ton of developer environment setup time.

**Comment by matthieudelaro** [comment]
OK, overloading configuration in macros would make Nut more flexible.
I'm not sure why it would be useful for golang-vscode though. You always use the same docker image, right?

**Comment by ctaggart** [comment]
That is a macro for a `nut.yml` that I would put in another go project. In this example, I would add it to `mygoproject`. Allowing the overloading would allow me to launch a Go IDE for a Go project and a .NET IDE for a .NET project. That would be killer.

**Comment by matthieudelaro** [comment]
So you mean, having the exact same `nut.yml` for a project in Go and for a project with .NET ?

**Comment by ctaggart** [comment]
No. A .NET project would have a different `code` macro that would launch a Visual Studio Code environment with .NET support. I want to be able to:

```
git clone https://github.com/ctaggart/SourceLink.git
nut code
```

Since it is a .NET project, it would have nut.yml with:
```
macros:
  code:
    docker-image: ctaggart/dotnet-vscode
    enable_gui: true
    mount:
      main:
      - .
      - /home/vscode/sourcelink
    usage: start vscode to edit this project
    actions:
    - su vscode -c "code -w /home/vscode/sourcelink"
```
