### ISSUE TITLE
How to add arguments to the commands

### ISSUE THREAD

**Issue by GreggJensen** [matthieudelaro/nut#29]
I am running with the latest version of nut, on OS X, and it works great for a command in a container, when there is only one argument to nut.  So, I have an s3cmd command in a docker container.  I set up the nut.yml to be:
```
syntax_version: "7"
project_name: s3cmd
volumes: 
  main: # give each folder any name that you like
    host_path: .  
    container_path: /root/s3cmd-workspace 

macros:
  s3cmd:
    usage: s3cmd to run against s3 storage

docker_image: s3cmd
environment: # set environment variables
    AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
    AWS_SECRET_KEY: ${AWS_SECRET_KEY}
```
then I run with nut s3cmd  and it shows the s3cmd usage.  So, in order to make it do something meaningful, the command would be (way simplified) 'nut s3cmd ls'  and it just prints out the usage.  Giving more arguments to make the s3cmd really do what it is meant to do and the same usage message comes out.

Added --log and ran it again with all the arguments and the very first line says:
DEBU[0000] commands (len = 0) : []

I tried some containers with X clients in them and they work great with nut (without needed socat), so this seems to be on the right path.  Just need to be able to give arguments.  Maybe I am supposed to use one of the other options or not make the command a macro in the nut.yml?
